USE Atelier2
GO

SET NUMERIC_ROUNDABORT OFF;

SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL,
ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS ON;
GO

CREATE VIEW View_Worker With SCHEMABINDING, ENCRYPTION
AS
SELECT IDWorker, Surname, Salary 
FROM dbo.Worker
WHERE Salary > 20000
GO

CREATE Unique CLUSTERED INDEX Index_On_View ON View_Worker (IDWorker) 

SET STATISTICS TIME ON;

SELECT * 
FROM View_Worker
GO

SET STATISTICS TIME OFF;

DROP VIEW View_Worker

DROP INDEX Index_On_View ON  View_Worker